---
name: Radarr
version: dev
slug: radarr
description: A fork of Sonarr to work with movies à la Couchpotato.
url: https://github.com/lbouriez/hassio-addons
image: ghcr.io/lbouriez/addon-radarr/{arch}
arch:
  - aarch64
  - amd64
  - armv7
init: false
webui: "http://[HOST]:[PORT:7878]"
panel_icon: "mdi:selection-ellipse"
ports:
  7878/tcp: 7878
ports_description:
  7878/tcp: The port for the Radarr webinterface
full_access: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
map:
  - share:rw
  - ssl:ro
  - media:rw
environment:
  PUID: "0"
  PGID: "0"
options:
  networkdisks: []
  cifsusername: "<username>"
  cifspassword: "<password>"
  cifsversion: 3.0
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  networkdisks:
    - str
  cifsusername: str
  cifspassword: str
  cifsversion: list(3.0|2.1|2.0|1.0)?
